import socket
import Encryption_handler

from colors import *

PRIMARY_SERVER_IP = "127.0.0.1"
PRIMARY_SERVER_PORT = 5555
PRIMARY_ADDRESS = (PRIMARY_SERVER_IP, PRIMARY_SERVER_PORT)


SECONDARY_SERVER_IP = "127.0.0.1"
SECONDARY_SERVER_PORT = 7890
SECONDARY_ADDRESS = (SECONDARY_SERVER_IP, SECONDARY_SERVER_PORT)


KEY_SIZE = 500
RECEIVE_SIZE = 4000


